[build]
  publish = "."

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[identity]
  # Enable Git Gateway
  git_gateway = true

[context.production.environment]
  HUGO_VERSION = "0.58.2"
