site_title: "Keyword Tool Tutorials"
site_description: "Learn how to use Keyword Tool with our comprehensive tutorials and guides"
logo: "/assets/logo.png"
contact_email: "support@keywordtool.io"
social:
  twitter: ""
  linkedin: ""
  youtube: ""
