backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Enable local development
local_backend: true

# Enable media uploads
media_folder: "assets/uploads" # Media files will be stored in the repo under assets/uploads
public_folder: "/assets/uploads" # The src attribute for uploaded media will begin with /assets/uploads

# Collections define the structure for different content types
collections:
  - name: "tutorials"
    label: "Tutorials"
    folder: "_tutorials"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Category", name: "category", widget: "select", options: ["Basics", "Find Keywords", "Check Search Volume", "Keyword Basket", "My Account"]}
      - {label: "Difficulty", name: "difficulty", widget: "select", options: ["Beginner", "Intermediate", "Advanced"]}
      - {label: "Duration", name: "duration", widget: "string", hint: "e.g., '5 minutes'"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Video URL", name: "video_url", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}

  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "index.html"
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Welcome Message", name: "welcome_message", widget: "text"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Featured Tutorials", name: "featured_tutorials", widget: "list", field: {label: "Tutorial", name: "tutorial", widget: "string"}}

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General Settings"
        name: "general"
        file: "_data/settings.yml"
        fields:
          - {label: "Site Title", name: "site_title", widget: "string"}
          - {label: "Site Description", name: "site_description", widget: "text"}
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Contact Email", name: "contact_email", widget: "string"}
          - {label: "Social Media", name: "social", widget: "object", fields: [
              {label: "Twitter", name: "twitter", widget: "string", required: false},
              {label: "LinkedIn", name: "linkedin", widget: "string", required: false},
              {label: "YouTube", name: "youtube", widget: "string", required: false}
            ]}

  - name: "navigation"
    label: "Navigation"
    files:
      - label: "Main Navigation"
        name: "main_nav"
        file: "_data/navigation.yml"
        fields:
          - {label: "Navigation Items", name: "nav_items", widget: "list", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "URL", name: "url", widget: "string"},
              {label: "Icon", name: "icon", widget: "string", hint: "Ionicon name"},
              {label: "Category", name: "category", widget: "string", required: false}
            ]}

# Enable editorial workflow
publish_mode: editorial_workflow

# Enable drafts
show_preview_links: true
